Insurance<-read.csv("C:\\Users\\admin\\Desktop\\Jigsaw\\Datsets\\insurance.csv")
dim(Insurance)
summary(Insurance)
colSums(is.na(Insurance))
str(Insurance)
Insurance$bmi<-ifelse(is.na(Insurance$bmi),round(mean(Insurance$bmi,na.rm=TRUE,digits=2)),
                      as.numeric(Insurance$bmi))


x<-boxplot(Insurance$age,col="red")
Index<-which(Insurance$age%in%x$out)
Insurance$age[Index]<-median(Insurance$age)
x<-boxplot(Insurance$bmi,col="red")
summary(Insurance$bmi)
Index<-which(Insurance$bmi%in%x$out)
Insurance$bmi<-ifelse(Insurance$bmi>46.75,46.75,as.numeric(Insurance$bmi))
Insurance$smoker1<-ifelse(Insurance$smoker=="yes",1,0)
Insurance$smoker1<-as.factor(Insurance$smoker1)
boxplot(Insurance$charges,Insurance$region)
plot(Insurance$region,Insurance$charges,col="red")
Insurance$region1<-ifelse(Insurance$region=="northwest"|Insurance$region=="southwest",
                          "nw-sw",as.character(Insurance$region))
Insurance$region1<-as.factor(Insurance$region1)
plot(Insurance$region1,Insurance$charges,col="red")
Insurance$children<-as.factor(Insurance$children)
plot(Insurance$children,Insurance$charges,col="red")
Insurance$children<-as.numeric(Insurance$children)
Insurance$NE_D<-ifelse(Insurance$region1=="northeast",1,0)
Insurance$SE_D<-ifelse(Insurance$region1=="southeast",1,0)
Insurance$NW_SW_D<-ifelse(Insurance$region1=="nw-sw",1,0)
Insurance$Gender_D<-ifelse(Insurance$sex=="male",1,0)
names(Insurance)
Ins<-Insurance[,-c(2,5,6,9)]
dim(Ins)
names(Ins)
Index<-sample(1:nrow(Ins),size = nrow(Ins)*.7,replace = FALSE)
InsTrain<-Ins[Index,]
InsTest<-Ins[-Index,]
dim(InsTrain)
dim(InsTest)
Mod<-lm(charges~.,data = InsTrain)
summary(Mod)
Mod1<-lm(charges~age+bmi+children+smoker1,data = InsTrain)
summary(Mod1)
hist(Mod1$residuals,col="orange")
qqPlot(Mod1$residuals)
vif(Mod1)
plot(Mod1$fitted.values,Mod1$residuals)
Mod2<-lm(log(charges)~age+bmi+children+smoker1,data = InsTrain)
summary(Mod2)
hist(Mod2$residuals,col="orange")
qqPlot(Mod2$residuals)
vif(Mod2)
plot(Mod2$fitted.values,Mod2$residuals)
Mod3<-lm(charges~log(age)+log(bmi)+children+smoker1,data = InsTrain)
summary(Mod3)
qqPlot(Mod3$residuals)
plot(Mod3$fitted.values,Mod3$residuals)
Mod4<-lm(charges~bmi+children+smoker1,data = InsTrain)
summary(Mod4)
hist(Mod4$residuals)
qqPlot(Mod4$residuals)
vif(Mod4)
plot(Mod4$fitted.values,Mod4$residuals)
Mod5<-lm(charges~sqrt(age)+bmi+children+smoker1,data = InsTrain)
summary(Mod5)
plot(Mod5$fitted.values,Mod5$residuals)
vif(Mod5)
hist(Mod5$residuals)
qqPlot(Mod5$residuals)
PredicedValue<-predict(Mod5,newdata=InsTest)
NewIns<-data.frame(InsTest,PredicedValue)
dim(NewIns)
names(NewIns)
plot(NewIns$charges,type="l",col="red")
lines(NewIns$PredicedValue,col="blue")

